# Our Custom Resource Definition for PodBuggerTool
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: podbuggertool.ualter.com
spec:
  group: ualter.com
  version: v1beta1
  names:
    kind: Podbuggertool
    plural: podbuggertools
    singular: podbuggertool
    shortNames:
      - pbt
  # either Namespaced or Cluster  
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            label:
              type: string
            image:
              type: string
          required:
            - image
            - key