apiVersion: apps/v1
kind: Deployment
metadata:
  name: podbuggertool
spec:
  replicas: 1
  selector:
    matchLabels:
      app: podbuggertool
  template:
    metadata:
      labels:
        app: podbuggertool
    spec:
      containers:
      - name: podbuggertool
        image: "ualter/podbuggertool:0.1.0"
        imagePullPolicy: IfNotPresent
        #image: "ualter/podbuggertool:latest"
        #imagePullPolicy: Always